# script.py.mako
"""add notifications table

Revision ID: 528392eb1bc9
Revises: cce16059d483
Create Date: 2026-04-14 22:09:38.769032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528392eb1bc9'
down_revision = 'cce16059d483'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
